# Generated by Django 6.1 on 2026-08-14 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Bahor Cafe', max_length=255)),
                ('city', models.CharField(blank=True, default="Farg'ona", max_length=255)),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderFlowSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_kitchen', models.BooleanField(default=True)),
                ('signal', models.BooleanField(default=True)),
                ('bill_btn', models.BooleanField(default=True)),
                ('served', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_flow_settings', to='sozlamalar.branch')),
            ],
            options={
                'verbose_name': 'Order Flow Settings',
            },
        ),
        migrations.CreateModel(
            name='ReceiptSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cafe_name', models.CharField(default='Bahor Cafe', max_length=255)),
                ('address', models.CharField(default="Toshkent sh., Mustaqillik ko'chasi", max_length=500)),
                ('phone', models.CharField(default='+998901234567', max_length=50)),
                ('footer_text', models.CharField(default="Telegram kanalimizga obuna bo'ling!", max_length=500)),
                ('show_cafe_name', models.BooleanField(default=True)),
                ('show_sana', models.BooleanField(default=True)),
                ('show_ish_vaqti', models.BooleanField(default=True)),
                ('show_sotuvchi', models.BooleanField(default=True)),
                ('show_kassir', models.BooleanField(default=True)),
                ('show_mijoz', models.BooleanField(default=True)),
                ('show_kontaktlar', models.BooleanField(default=True)),
                ('show_inn', models.BooleanField(default=True)),
                ('show_yuridik_shaxs', models.BooleanField(default=True)),
                ('show_manzil', models.BooleanField(default=False)),
                ('show_mijoz_raqami', models.BooleanField(default=True)),
                ('show_eslatma', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_settings', to='sozlamalar.branch')),
            ],
            options={
                'verbose_name': 'Receipt Settings',
            },
        ),
        migrations.CreateModel(
            name='RestaurantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Bahor Cafe', max_length=255)),
                ('address', models.CharField(default="Toshkent sh., Mustaqillik ko'chasi", max_length=500)),
                ('phone', models.CharField(default='+998 90 123 45 67', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_settings', to='sozlamalar.branch')),
            ],
            options={
                'verbose_name': 'Restaurant Settings',
                'verbose_name_plural': 'Restaurant Settings',
            },
        ),
        migrations.CreateModel(
            name='TaxSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('service_percent', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('calculation_type', models.CharField(choices=[('auto', 'Avtomatik'), ('manual', "Qo'lda")], default='auto', max_length=20)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_settings', to='sozlamalar.branch')),
            ],
            options={
                'verbose_name': 'Tax & Service Settings',
            },
        ),
    ]
