# Generated by Django 6.1 on 2026-08-15 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sozlamalar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot_token', models.CharField(blank=True, default='', max_length=255)),
                ('chat_id', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('notify_order_paid', models.BooleanField(default=True, verbose_name="To'lov bo'lganda chek yuborish")),
                ('notify_order_cancelled', models.BooleanField(default=True, verbose_name='Bekor qilingan buyurtma xabari')),
                ('notify_daily_report', models.BooleanField(default=True, verbose_name='Kunlik hisobot yuborish')),
                ('daily_report_time', models.CharField(default='20:00', max_length=10)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_settings', to='sozlamalar.branch')),
            ],
            options={
                'verbose_name': 'Telegram Bot Settings',
                'verbose_name_plural': 'Telegram Bot Settings',
            },
        ),
    ]
