# Generated by Django 6.1 on 2026-08-14 10:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('order', '0001_initial'),
        ('sozlamalar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('category_type', models.CharField(choices=[('INCOME', 'Daromad'), ('EXPENSE', 'Xarajat')], default='EXPENSE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Finance Categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FinanceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('CASH', 'Naqd pul (Kassa)'), ('NON_CASH', 'Plastik karta (Terminal)'), ('BANK', 'Hisob raqam (Bank)')], default='CASH', max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('currency', models.CharField(default='UZS', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_accounts', to='sozlamalar.branch')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FinanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Kirim / Daromad'), ('EXPENSE', 'Chiqim / Xarajat')], default='INCOME', max_length=20)),
                ('payment_type', models.CharField(default='cash', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('source', models.CharField(choices=[('kassa', 'Kassa sotuv tushumi'), ('order', "Buyurtma to'lovi"), ('salary', "Maosh to'lovi"), ('purchase', 'Ombor xaridi'), ('manual', "Qo'lda kiritilgan")], default='manual', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.financeaccount')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_transactions', to='sozlamalar.branch')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.financecategory')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_transactions', to='employee.employee')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_transactions', to='order.order')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
