# Generated by Django 6.1 on 2026-08-15 07:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financetransaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
