# Generated by Django 6.1 on 2026-08-14 10:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('sozlamalar', '0001_initial'),
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField(blank=True, db_index=True, null=True)),
                ('type', models.CharField(choices=[('dine_in', 'Zalda (Dine-in)'), ('takeaway', 'Olib ketish (Takeaway)'), ('delivery', 'Yetkazib berish (Delivery)')], default='dine_in', max_length=50)),
                ('status', models.CharField(choices=[('open', 'Ochiq'), ('sent_to_kitchen', 'Oshxonaga yuborilgan'), ('ready', 'Tayyor'), ('paid', "To'langan"), ('closed', 'Yopilgan'), ('cancelled', 'Bekor qilingan')], default='open', max_length=50)),
                ('guests_count', models.IntegerField(default=1)),
                ('base_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('discount_type', models.CharField(default='percent', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('service_percent', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('service_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('payment_type', models.CharField(blank=True, choices=[('cash', 'Naqd'), ('card', 'Plastik karta'), ('mixed', 'Aralash'), ('click', 'Click'), ('payme', 'Payme')], max_length=50, null=True)),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('card_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('note', models.TextField(blank=True, default='')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_waiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='employee.employee')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='sozlamalar.branch')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='table.table')),
                ('table_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='table.tablepart')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('cooking', 'Tayyorlanmoqda'), ('ready', 'Tayyor'), ('served', 'Yetkazildi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=50)),
                ('product_name_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('kitchen_name_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='table.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
