# Generated by Django 6.1 on 2026-08-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
